kind: Pod 
apiVersion: v1
metadata:
  name: multipod
  labels:    ## defining lables for pods is mandatory 
  	app: lapclass
	tier: prod
spec:
       containers:
        - name: cont1
          image: ushopwell/sampleapp:24
          ports:
            - name: http
              containerPort: 80
      - name: cont2
      	image: ushopwell/sampleapp:22
      	ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443